#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'p4c-bm==0.1.0','console_scripts','p4c-bmv2'
__requires__ = 'p4c-bm==0.1.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('p4c-bm==0.1.0', 'console_scripts', 'p4c-bmv2')()
    )
